INSERT INTO budgetBuddy.category(category_name, category_description,category_is_income) 
VALUES ('Housing','Property insurance, rent, mortgage payments, property taxes, home maintenance costs, ect.',False),
('Transportation','Auto insurance, vehicle payments, DMV fees, gas, tolls, parking, public transit, vehicle maintenance, ect.',False),
('Essential Groceries','Grocery items considered essential',False),
('Non-Essential Groceries','Grocery items considered non-essential ex: alcohol',False),
('Utilities','Water, electricity, HVAC, gas, phone, cable/internet, ect.',False),
('Insurance','Life insurance, disability insurance, and other miscellaneous insurances.',False),
('Medical','Health insurance, out-of-pocket primary care costs, specialty care, dental care, urgent care, prescriptions, medical supplies/devices, ect.',False),
('Investment','401(k) retirement account, IRAs, ETFs, stocks, savings bonds, non-liquid assets, ect.',False),
('Restaurant','Diners, drive-ins, dives, fast food, restaurants, ect.',False),
('Entertainment','Sporting events, concert tickets, vacation expenses, video games, movies, hobbies, ect.',False),
('Clothing','Shirts, blouses, pants, skirts, hats, jewlery, accessories, ect.',False),
('Gift','Presents for others.',False),
('Furnishings','Home decor, furniture, fittings, decorative accessories, curtains, carpets, ect.',False),
('Pet','Ownership, food, treats, housing, medical expenses, and anything else pertaining to ones hairy, furry, scaly, or feathery friends.',False),
('Tax Payment','Government tax payment',False),
('Miscellaneous Expense','Expenses that do not fit in other categories.',False),
('Job Income','Wages or salary from ones job.',True),
('Received Gift','Cash gift from another person.',True),
('Interest','Non-liquid funds made liquid, dividends, savings account interest, ect.',True),
('Government Payment','Assistance payments from the government.',True),
('Tax Refund','Government refund from taxes.',True),
('Miscellaneous Income','Incomes that do not fit in other categories.',True);