# Generated by Django 3.2.5 on 2021-09-27 21:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Users',
            fields=[
                ('first_name', models.CharField(help_text='Enter first name', max_length=20)),
                ('last_name', models.CharField(help_text='Enter last name', max_length=20)),
                ('display_name', models.CharField(help_text='Enter the a name for which you would like others on the platform to see you.', max_length=20)),
                ('id', models.AutoField(primary_key=True, serialize=False)),
            ],
            options={
                'ordering': ['id', 'display_name', '-first_name', '-last_name'],
            },
        ),
    ]
