# Generated by Django 3.2.7 on 2022-02-03 19:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='challenge',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='challengetrigger',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='competition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='expense',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='experience',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='friend',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='globalcompetition',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='income',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='item',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='notification',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='receipt',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='securityquestion',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usercategorybudget',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userchallengeinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='useriteminventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='usernotificationlist',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='users',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='userwidgetinventory',
            options={'managed': False},
        ),
        migrations.AlterModelOptions(
            name='widget',
            options={'managed': False},
        ),
    ]
