# Generated by Django 3.2.7 on 2021-11-03 18:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='challenge',
            name='active',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[01]+$', message='The string can only include 0s or 1s.')]),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_repeatable',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[01]+$', message='The string can only include 0s or 1s.')]),
        ),
        migrations.AlterField(
            model_name='challengeinventory',
            name='challenge_completion',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[01]+$', message='The string can only include 0s or 1s.')]),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipped',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[01]+$', message='The string can only include 0s or 1s.')]),
        ),
        migrations.AlterField(
            model_name='users',
            name='email',
            field=models.EmailField(blank=True, max_length=255, null=True, unique=True, validators=[django.core.validators.EmailValidator()], verbose_name='email address'),
        ),
        migrations.AlterField(
            model_name='users',
            name='notifications',
            field=models.CharField(blank=True, max_length=1, null=True, validators=[django.core.validators.RegexValidator('^[01]+$', message='The string can only include 0s or 1s.')]),
        ),
    ]
