# Generated by Django 3.2.7 on 2021-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_auto_20211103_1443'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='category_description',
        ),
        migrations.AddField(
            model_name='category',
            name='category_income',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='active',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challenge',
            name='challenge_repeatable',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='challengeinventory',
            name='challenge_completion',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='inventory',
            name='equipped',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='users',
            name='notifications',
            field=models.BooleanField(blank=True, null=True),
        ),
    ]
