# Generated by Django 3.2.7 on 2021-12-01 15:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20211201_1022'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='is_income',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='receipt',
            name='reoccuring',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
